version: '3.7'
services:
  rop:
    container_name: rop
    build:
      context: ../
      dockerfile: Dockerfile
    security_opt:
      - seccomp:unconfined
    ports:
      - "2222:22"
    tty: true
    stdin_open: true

  